// Real, generated PDF practice sheets (jsPDF) — replaces the old window.print()
// flow. Clicking download produces an actual .pdf blob that downloads immediately
// (no browser print dialog), named after the song, with the decorative watercolor
// as a full-bleed background on EVERY page and readable text over a soft scrim.
//
// renderSheetDoc is pure (jsPDF only, no window/fetch) so it can be exercised in a
// Node test; downloadSongPdf adds the browser bits (fetch the image, save the file).

import { jsPDF } from 'jspdf';
import type { Song } from '../types';
import { sanitizeFilename, parseSheetContent } from './pdfSheetLayout.ts';

export { sanitizeFilename, parseSheetContent } from './pdfSheetLayout.ts';

const A4_W = 210, A4_H = 297, MARGIN = 15, FOOTER_H = 12;

/** Build the PDF document for a song. bgDataUrl (PNG data URI) is painted full-bleed
 *  on every page; pass null to fall back to a plain tint. No DOM/network here. */
export const renderSheetDoc = (song: Song, bgDataUrl: string | null): jsPDF => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });

  const paintBackground = () => {
    if (bgDataUrl) {
      try { doc.addImage(bgDataUrl, 'PNG', 0, 0, A4_W, A4_H, undefined, 'FAST'); } catch { /* fall back to tint */ }
    } else {
      doc.setFillColor(255, 253, 249); doc.rect(0, 0, A4_W, A4_H, 'F');
    }
    try {
      doc.saveGraphicsState();
      // @ts-ignore - GState provided by jsPDF at runtime
      doc.setGState(new (doc as any).GState({ opacity: 0.5 }));
      doc.setFillColor(255, 250, 240);
      doc.rect(0, 0, A4_W, A4_H, 'F');
      doc.restoreGraphicsState();
    } catch { /* opacity unsupported → skip */ }
  };

  const footer = (pageNo: number) => {
    doc.setFont('helvetica', 'bold'); doc.setFontSize(7); doc.setTextColor(146, 64, 14);
    doc.text('GENERATED BY PLECTRUM', MARGIN, A4_H - 6);
    doc.text(`PAGE ${pageNo}`, A4_W - MARGIN, A4_H - 6, { align: 'right' });
  };

  let page = 1;
  paintBackground();

  // Header band
  doc.setFillColor(45, 27, 21); doc.roundedRect(MARGIN, MARGIN, A4_W - MARGIN * 2, 26, 2, 2, 'F');
  doc.setFont('helvetica', 'bold'); doc.setFontSize(20); doc.setTextColor(255, 247, 237);
  doc.text((doc.splitTextToSize(song.title || 'Untitled', A4_W - MARGIN * 2 - 8) as string[])[0], MARGIN + 5, MARGIN + 11);
  doc.setFontSize(11); doc.setTextColor(251, 191, 36);
  doc.text(song.artist || '', MARGIN + 5, MARGIN + 18);
  const meta = [song.key ? `Key ${song.key}` : '', `Capo ${song.capo ?? 0}`, song.strummingPattern ? `Strum ${song.strummingPattern}` : '', song.difficulty || 'Practice'].filter(Boolean).join('   ');
  doc.setFontSize(8); doc.setTextColor(255, 247, 237);
  doc.text(meta, A4_W - MARGIN - 5, MARGIN + 22, { align: 'right' });

  let y = MARGIN + 26 + 8;
  const contentW = A4_W - MARGIN * 2;
  const chordColW = 55;
  const lyricW = contentW - chordColW - 4;

  const ensureSpace = (need: number) => {
    if (y + need > A4_H - FOOTER_H) {
      footer(page); doc.addPage(); page += 1; paintBackground(); y = MARGIN;
    }
  };

  for (const line of parseSheetContent(song.content)) {
    if (line.kind === 'spacer') { y += 3.5; continue; }
    if (line.kind === 'section') {
      ensureSpace(10); y += 3;
      doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(124, 61, 6);
      doc.text(line.text.toUpperCase(), MARGIN, y);
      doc.setDrawColor(217, 154, 74); doc.setLineWidth(0.4); doc.line(MARGIN, y + 1.5, MARGIN + contentW, y + 1.5);
      y += 6.5;
      continue;
    }
    doc.setFont('helvetica', 'normal'); doc.setFontSize(11); doc.setTextColor(28, 20, 13);
    const wrapped = doc.splitTextToSize(line.text || ' ', lyricW) as string[];
    const blockH = Math.max(wrapped.length * 5.2, 5.2);
    ensureSpace(blockH + 1);
    doc.text(wrapped, MARGIN, y);
    if (line.chords.length) {
      doc.setFont('courier', 'bold'); doc.setFontSize(10); doc.setTextColor(120, 53, 15);
      doc.text(line.chords.join('  '), MARGIN + contentW, y, { align: 'right' });
    }
    y += blockH + 1.5;
  }

  footer(page);
  return doc;
};

// ── Browser download ──────────────────────────────────────────────────────────
const loadImageDataUrl = async (url: string): Promise<string | null> => {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const blob = await res.blob();
    return await new Promise<string>((resolve, reject) => {
      const r = new FileReader();
      r.onload = () => resolve(r.result as string);
      r.onerror = reject;
      r.readAsDataURL(blob);
    });
  } catch { return null; }
};

let inFlight = false; // guard against double-download from rapid clicks

/** Generate + download a PDF for a song. Immediate download, no print dialog. */
export const downloadSongPdf = async (song: Song): Promise<string> => {
  if (inFlight) return sanitizeFilename(song.title);
  inFlight = true;
  try {
    const bg = await loadImageDataUrl(`${window.location.origin}/sheet-bg.png`);
    const doc = renderSheetDoc(song, bg);
    const filename = sanitizeFilename(song.title);
    doc.save(filename); // immediate blob download — no print dialog
    return filename;
  } finally {
    setTimeout(() => { inFlight = false; }, 400);
  }
};
