// Real, generated PDF practice sheets (jsPDF). Instant download, no print dialog,
// filename = song title, full-bleed watercolor background on every page.
//
// Two render paths:
//  • Latin text  → jsPDF vector text (crisp, small, selectable).  [renderSheetDoc]
//  • Complex/non-Latin script (Gujarati, Hindi, Tamil, Arabic, …) → the browser
//    renders the text to a transparent canvas (it has the right fonts; jsPDF's
//    built-in fonts do not) which is placed over the background.  [renderSheetViaCanvas]
//
// renderSheetDoc is pure (jsPDF only) and Node-testable; the canvas path is
// browser-only and lazy-imports html2canvas.

import { jsPDF } from 'jspdf';
import type { Song } from '../types';
import { sanitizeFilename, parseSheetContent, hasComplexScript } from './pdfSheetLayout.ts';

export { sanitizeFilename, parseSheetContent, hasComplexScript } from './pdfSheetLayout.ts';

const A4_W = 210, A4_H = 297, MARGIN = 15, FOOTER_H = 12;
const CONTENT_W = A4_W - MARGIN * 2; // 180mm

/** Paint the full-bleed background + frosted scrim on the current page. */
const paintPageBackground = (doc: jsPDF, bg: string | null) => {
  if (bg) {
    try { doc.addImage(bg, 'PNG', 0, 0, A4_W, A4_H, undefined, 'FAST'); } catch { doc.setFillColor(255, 253, 249); doc.rect(0, 0, A4_W, A4_H, 'F'); }
  } else { doc.setFillColor(255, 253, 249); doc.rect(0, 0, A4_W, A4_H, 'F'); }
  try {
    doc.saveGraphicsState();
    // @ts-ignore GState provided at runtime
    doc.setGState(new (doc as any).GState({ opacity: 0.5 }));
    doc.setFillColor(255, 250, 240); doc.rect(0, 0, A4_W, A4_H, 'F');
    doc.restoreGraphicsState();
  } catch { /* opacity unsupported */ }
};

const drawFooter = (doc: jsPDF, pageNo: number) => {
  doc.setFont('helvetica', 'bold'); doc.setFontSize(7); doc.setTextColor(146, 64, 14);
  doc.text('GENERATED BY PLECTRUM', MARGIN, A4_H - 6);
  doc.text(`PAGE ${pageNo}`, A4_W - MARGIN, A4_H - 6, { align: 'right' });
};

/** Vector text path (Latin). Pure — no DOM/network. */
export const renderSheetDoc = (song: Song, bgDataUrl: string | null): jsPDF => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });
  let page = 1;
  paintPageBackground(doc, bgDataUrl);

  doc.setFillColor(45, 27, 21); doc.roundedRect(MARGIN, MARGIN, CONTENT_W, 26, 2, 2, 'F');
  doc.setFont('helvetica', 'bold'); doc.setFontSize(20); doc.setTextColor(255, 247, 237);
  doc.text((doc.splitTextToSize(song.title || 'Untitled', CONTENT_W - 8) as string[])[0], MARGIN + 5, MARGIN + 11);
  doc.setFontSize(11); doc.setTextColor(251, 191, 36);
  doc.text(song.artist || '', MARGIN + 5, MARGIN + 18);
  const meta = [song.key ? `Key ${song.key}` : '', `Capo ${song.capo ?? 0}`, song.strummingPattern ? `Strum ${song.strummingPattern}` : '', song.difficulty || 'Practice'].filter(Boolean).join('   ');
  doc.setFontSize(8); doc.setTextColor(255, 247, 237);
  doc.text(meta, A4_W - MARGIN - 5, MARGIN + 22, { align: 'right' });

  let y = MARGIN + 26 + 8;
  const chordColW = 55, lyricW = CONTENT_W - chordColW - 4;
  const ensureSpace = (need: number) => { if (y + need > A4_H - FOOTER_H) { drawFooter(doc, page); doc.addPage(); page += 1; paintPageBackground(doc, bgDataUrl); y = MARGIN; } };

  for (const line of parseSheetContent(song.content)) {
    if (line.kind === 'spacer') { y += 3.5; continue; }
    if (line.kind === 'section') {
      ensureSpace(10); y += 3;
      doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(124, 61, 6);
      doc.text(line.text.toUpperCase(), MARGIN, y);
      doc.setDrawColor(217, 154, 74); doc.setLineWidth(0.4); doc.line(MARGIN, y + 1.5, MARGIN + CONTENT_W, y + 1.5);
      y += 6.5; continue;
    }
    doc.setFont('helvetica', 'normal'); doc.setFontSize(11); doc.setTextColor(28, 20, 13);
    const wrapped = doc.splitTextToSize(line.text || ' ', lyricW) as string[];
    const blockH = Math.max(wrapped.length * 5.2, 5.2);
    ensureSpace(blockH + 1);
    doc.text(wrapped, MARGIN, y);
    if (line.chords.length) {
      doc.setFont('courier', 'bold'); doc.setFontSize(10); doc.setTextColor(120, 53, 15);
      doc.text(line.chords.join('  '), MARGIN + CONTENT_W, y, { align: 'right' });
    }
    y += blockH + 1.5;
  }
  drawFooter(doc, page);
  return doc;
};

// ── Complex-script path (browser): render text with the OS fonts to a canvas ──
const esc = (s: string) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const buildSheetHtml = (song: Song): string => {
  const meta = [song.key ? `Key ${esc(song.key)}` : '', `Capo ${esc(String(song.capo ?? 0))}`, song.strummingPattern ? `Strum ${esc(song.strummingPattern)}` : '', esc(song.difficulty || 'Practice')].filter(Boolean).join(' &nbsp; ');
  const rows = parseSheetContent(song.content).map(l => {
    if (l.kind === 'spacer') return '<div style="height:12px"></div>';
    if (l.kind === 'section') return `<div style="margin:16px 0 6px;color:#7c3d06;border-bottom:2px solid #d99a4a;padding-bottom:4px;font-size:15px;font-weight:800;letter-spacing:.06em;text-transform:uppercase;text-shadow:0 1px 3px rgba(255,250,240,.95)">${esc(l.text)}</div>`;
    const chords = l.chords.length ? `<span style="flex:0 0 auto;margin-left:14px;font-family:'Courier New',monospace;font-weight:800;color:#78350f">${esc(l.chords.join('  '))}</span>` : '';
    return `<div style="display:flex;justify-content:space-between;align-items:baseline;padding:4px 2px;font-size:18px;color:#1c140d;text-shadow:0 1px 3px rgba(255,250,240,.95),0 0 2px rgba(255,250,240,.9)"><span style="min-width:0;word-break:break-word">${esc(l.text) || '&nbsp;'}</span>${chords}</div>`;
  }).join('');
  const fonts = "'Noto Sans','Noto Sans Devanagari','Noto Sans Gujarati','Noto Sans Tamil','Noto Sans Bengali','Nirmala UI','Arial Unicode MS',system-ui,-apple-system,'Segoe UI',sans-serif";
  return `<div style="font-family:${fonts};line-height:1.6">
    <div style="background:linear-gradient(135deg,#2d1b15,#5d2f12);border-radius:8px;padding:14px 18px;margin-bottom:16px">
      <div style="color:#fff7ed;font-size:24px;font-weight:800">${esc(song.title || 'Untitled')}</div>
      <div style="color:#fbbf24;font-size:14px;margin-top:4px">${esc(song.artist || '')}</div>
      <div style="color:#fff7ed;font-size:11px;margin-top:6px;opacity:.9">${meta}</div>
    </div>${rows}</div>`;
};

/** Browser-only: render any script correctly by rasterising the text over the bg. */
export const renderSheetViaCanvas = async (song: Song, bg: string | null): Promise<jsPDF> => {
  const html2canvas = (await import('html2canvas')).default;
  const CW = 760; // content column width in CSS px, maps to CONTENT_W (180mm)
  const host = document.createElement('div');
  host.style.cssText = `position:fixed;left:-10000px;top:0;width:${CW}px;background:transparent;z-index:-1`;
  host.innerHTML = buildSheetHtml(song);
  document.body.appendChild(host);
  let canvas: HTMLCanvasElement;
  try {
    canvas = await html2canvas(host, { backgroundColor: null, scale: 2, logging: false, useCORS: true });
  } finally {
    document.body.removeChild(host);
  }

  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });
  const pxPerMm = canvas.width / CONTENT_W;              // canvas px per mm of content width
  const pageContentMm = A4_H - MARGIN - FOOTER_H;        // usable vertical mm per page
  const pageSlicePx = Math.max(1, Math.floor(pageContentMm * pxPerMm));
  let offset = 0, page = 0;
  while (offset < canvas.height) {
    if (page > 0) doc.addPage();
    paintPageBackground(doc, bg);
    const slicePx = Math.min(pageSlicePx, canvas.height - offset);
    const tmp = document.createElement('canvas');
    tmp.width = canvas.width; tmp.height = slicePx;
    tmp.getContext('2d')!.drawImage(canvas, 0, offset, canvas.width, slicePx, 0, 0, canvas.width, slicePx);
    doc.addImage(tmp.toDataURL('image/png'), 'PNG', MARGIN, MARGIN, CONTENT_W, slicePx / pxPerMm);
    drawFooter(doc, page + 1);
    offset += slicePx; page += 1;
    if (page > 60) break; // safety cap
  }
  return doc;
};

// ── Browser download ──────────────────────────────────────────────────────────
const loadImageDataUrl = async (url: string): Promise<string | null> => {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const blob = await res.blob();
    return await new Promise<string>((resolve, reject) => {
      const r = new FileReader();
      r.onload = () => resolve(r.result as string);
      r.onerror = reject;
      r.readAsDataURL(blob);
    });
  } catch { return null; }
};

let inFlight = false;

/** Generate + download a PDF for a song. Immediate download, no print dialog. */
export const downloadSongPdf = async (song: Song): Promise<string> => {
  if (inFlight) return sanitizeFilename(song.title);
  inFlight = true;
  try {
    const bg = await loadImageDataUrl(`${window.location.origin}/sheet-bg.png`);
    const complex = hasComplexScript(`${song.title} ${song.content}`);
    const doc = complex ? await renderSheetViaCanvas(song, bg) : renderSheetDoc(song, bg);
    const filename = sanitizeFilename(song.title);
    doc.save(filename);
    return filename;
  } finally {
    setTimeout(() => { inFlight = false; }, 400);
  }
};
